chore(makefiles): update makefile.secrets

diff --git a/templates/makefiles/Makefile.secrets b/templates/makefiles/Makefile.secrets
--- a/templates/makefiles/Makefile.secrets
+++ b/templates/makefiles/Makefile.secrets
@@ -18,6 +18,12 @@ open:
 	    UNSAFE_FILE=$${GPG_FILE%.gpg} ; \
 	    if [ "$$GPG_FILE" -nt "$$UNSAFE_FILE" ] ; then \
 	        gpg -d "$$GPG_FILE" > "$$UNSAFE_FILE"; \
+	        rv=$$? ; \
+	        if [ "$$rv" != "0" ] ; then \
+	            rm "$$UNSAFE_FILE" ; \
+	            echo -e "\nERROR ($$rv): opening $$GPG_FILE" ; \
+	            break ; \
+	        fi ; \
 	    else \
 	        echo "Already open: $$GPG_FILE" ; \
 	    fi ; \
@@ -30,9 +36,8 @@ open:
 clean-gpg:
 	for EXT in asc gpg ; do \
 	    find . -iname "*.$$EXT" | while read GPG_FILE ; do \
-	        DELETE_ME=$${GPG_FILE%.asc} ; \
-	        DELETE_ME=$${GPG_FILE%.gpg} ; \
-	        rm -rfv "$$DELETE_ME";  \
+	        DELETE_ME=$${GPG_FILE%.$$EXT} ; \
+	        rm -rfv "$$DELETE_ME"; \
 	    done ; \
 	done ; \
 	for EXT in key sec ; do \
@@ -52,7 +57,7 @@ _reencrypt: check_realpath
 	done ; \
 	find . -iname "*.gpg" | while read GPG_FILE ; do \
 	    UNSAFE_FILE=$${GPG_FILE%.gpg} ; \
-	        if [ "$(FORCE_REENCRYPT)" = "yes" -o "$$UNSAFE_FILE" -nt "$$GPG_FILE" ] ; then \
+	    if [ "$(FORCE_REENCRYPT)" = "yes" -o "$$UNSAFE_FILE" -nt "$$GPG_FILE" ] ; then \
 	        echo "** UPDATING $$GPG_FILE" ; \
 	        gpg --yes -e $$RECIPIENTS "$$UNSAFE_FILE" ; \
 	    else \
