[makefiles] upd makefile.secrets

diff --git a/templates/makefiles/Makefile.secrets b/templates/makefiles/Makefile.secrets
--- a/templates/makefiles/Makefile.secrets
+++ b/templates/makefiles/Makefile.secrets
@@ -4,6 +4,15 @@
 
 GPG_DIR=resources/gpg-keys
 
+check_realpath:
+	@if ! realpath / --relative-to . > /dev/null 2>&1 ; then \
+	    echo "ERROR: realpath command: you are probably on a mac." ; \
+	    echo "       please install the GNU coreutils and use these" ; \
+	    echo "       in your shell: brew install coreutils" ; \
+	    false ; \
+	fi
+.PHONY: check_realpath
+
 open:
 	find . -iname "*.gpg" | while read GPG_FILE ; do \
 	    UNSAFE_FILE=$${GPG_FILE%.gpg} ; \
@@ -35,7 +44,7 @@ clean-gpg:
 .SILENT: clean-gpg
 
 # https://security.stackexchange.com/a/86751
-_reencrypt:
+_reencrypt: check_realpath
 	REPO_ROOT=$$(realpath --relative-to=. $$(git rev-parse --show-toplevel)) ; \
 	RECIPIENTS="" ; \
 	for RECIPIENT in "$$REPO_ROOT/$(GPG_DIR)/"* ; do \
